openapi: 3.0.1
info:
  title: ULCA - service schema
  description: The documentation defines the model.
  contact:
    name: ekstep foundation
    email: contact@ekstep.org
  version: 1.0.0
servers:
  - url: /ulca
paths: {}
components:
  schemas:
    EndToEndPipeline:
      required:
        - callbackUrl
        - masterApiKey
        - supportedPipelines
      type: object
      properties:
        callbackUrl:
          type: string
          format: url
        supportedPipelines:
          $ref: "#/components/schemas/PipelineList"
        masterApiKey:
          required:
            - value
          type: object
          description: if endpoint needs authorization in headers to fetch output
          properties:
            name:
              type: string
              description: >-
                expected if the callbackurl requires an API key with a
                particular name. `Authorization` will be considered as default
                name if value is provided without a name
              default: Authorization
              example: apiKey
            value:
              type: string
              description: >-
                expected if the callbackurl requires an API key so as to fetch
                output
              example: dde19858-b354-4e24-8e92-a7a4b320c066
    
    PipelineList:
      type: array
      items: 
        $ref: "#/components/schemas/SupportedTasks"
      
    SupportedTasks:
        type: array
        items:
          anyOf: 
          $ref: https://raw.githubusercontent.com/ULCA-IN/ulca/master/specs/common-schemas.yml#/components/schemas/SupportedTasks


