openapi: 3.0.0
info:
  title: API Key Generation and Revoking Schema
  description: The document defines request to generate and revoke service end point api key for ULCA.
  contact:
    name: ekstep foundation
    email: contact@ekstep.org
  version: 1.0.0
servers:
  - url: /ulca
paths: {}
components:
  schemas:
  
    APIKeyGenerationRequest:
      required:
        - userDetails
        - email
      type: object
      properties:
        userDetails:
          type: string
          description: AppName and User API Key (ULCA) separated by /
          example: BhashiniAndroid/34rtegregy43b
        email:
          type: string

    APIKeyGenerationResponse:
      required:
        - ApiKey
      type: object
      properties:
        ApiKey:
          required:
            - value
          type: object
          properties:
            name:
              type: string
              description: expected if the callbackurl requires an API key with a particular name. `Authorization` will be considered as default name if value is provided without a name
              default: Authorization
              example: apiKey
            value:
              type: string
              description: expected if the callbackurl requires an API key so as to fetch output
              example: dde19858-b354-4e24-8e92-a7a4b320c066

    APIKeyRevokeRequest:
      required:
        - userDetails
        - email
        - ApiKey
      type: object
      properties:
        userDetails:
          type: string
          description: AppName and User API Key (ULCA) separated by /
          example: BhashiniAndroid/34rtegregy43b
        email:
          type: string
        ApiKey:
          required:
            - value
          type: object
          properties:
            name:
              type: string
              description: expected if the callbackurl requires an API key with a particular name. `Authorization` will be considered as default name if value is provided without a name
              default: Authorization
              example: apiKey
            value:
              type: string
              description: expected if the callbackurl requires an API key so as to fetch output
              example: dde19858-b354-4e24-8e92-a7a4b320c066

    APIKeyRevokeResponse:
      required:
        - message
      type: object
      properties:
        message:
          type: string
          description: A success message "API Key successfully revoked" if or a failure message describing the error faced such as "API Key not found".
          example: API Key successfully revoked

