openapi: 3.0.1
info:
  title: ULCA - service schema
  description: The documentation defines the model.
  contact:
    name: ekstep foundation
    email: contact@ekstep.org
  version: 1.0.0
servers:
  - url: /ulca
paths: {}
components:
  schemas:
    PipelineInference:
      required:
        - submitter
        - inferenceEndPoint
        - supportedPipelines
      type: object
      properties:
        submitter:
          $ref: https://raw.githubusercontent.com/ULCA-IN/ulca/master/specs/common-schemas.yml#/components/schemas/Submitter
        inferenceEndPoint:
          $ref: 'https://raw.githubusercontent.com/ULCA-IN/ulca/specs-changes/specs/model-schema.yml#/components/schemas/InferenceAPIEndPoint'
        supportedPipelines:
          $ref: "#/components/schemas/ListOfPipelines"
    
    ListOfPipelines:
      type: array
      items: 
        $ref: "#/components/schemas/PipelineTaskSequence"
      
    PipelineTaskSequence:
        type: array
        items:
          anyOf: 
          $ref: https://raw.githubusercontent.com/ULCA-IN/ulca/master/specs/common-schemas.yml#/components/schemas/SupportedTasks

    InferenceAPIEndPoint:
      required:
        - callbackUrl
      type: object
      properties:
        callbackUrl:
          type: string
          format: url
        inferenceApiKey:
          required:
            - value
          type: object
          description: if endpoint needs authorization in headers to fetch output
          properties:
            name:
              type: string
              description: expected if the callbackurl requires an API key with a particular name. `Authorization` will be considered as default name if value is provided without a name
              default: Authorization
              example: apiKey
            value:
              type: string
              description: expected if the callbackurl requires an API key so as to fetch output
              example: dde19858-b354-4e24-8e92-a7a4b320c066
        isMultilingualEnabled:
          type: boolean
          default: false
          description: specify true if the same callbackUrl is capable of handling multiple languages
        isSyncApi:
          type: boolean
          description: specify true if the inference is a sync api, false otherwise. when false, specify the polling url and related properties
        asyncApiDetails:
          $ref: 'https://raw.githubusercontent.com/ULCA-IN/ulca/master/specs/model-schema.yml#/components/schemas/AsyncApiDetails'
        
      description: hosted location defines the end point of the model inference. specify a taskType along with Inference type

