openapi: 3.0.0
info:
  title: Pipeline feedback schema
  description: The document defines request and response to collect feedback for a pipeline submitted to ULCA
  contact:
    name: ekstep foundation
    email: contact@ekstep.org
  version: 1.2.0
servers:
  - url: /ulca
paths: {}
components:
  schemas:
    PipelineFeedbackRequest:
      required:
        - pipelineId
        - pipelineInput
      type: object
      properties:
        pipelineId:
          type: string
          description: ID of the pipeline submitter
          example: AI4BharatID
        feedbackTimeStamp:
          type: string
          description: timestamp when feedback is provided
        pipelineFeedback:
            type: object
            required:
             - feedback
            properties:
              feedback:
                type: array
                description : list of
                items:
                   $ref: '#/components/schemas/Feedback'
        taskFeedback:
          type: array
          description: list of
          items:
            $ref: '#/components/schemas/TaskFeedback'
        pipelineInput:
          $ref: https://raw.githubusercontent.com/ULCA-IN/ulca/specs-changes/specs/compute-pipeline-schemas.yml#/components/schemas/PipelineComputeRequest
        pipelineOutput:
          $ref: https://raw.githubusercontent.com/ULCA-IN/ulca/specs-changes/specs/compute-pipeline-schemas.yml#/components/schemas/PipelineComputeResponse
        expectedPipelineOutput:
          $ref: https://raw.githubusercontent.com/ULCA-IN/ulca/specs-changes/specs/compute-pipeline-schemas.yml#/components/schemas/PipelineComputeResponse
        
    PipelineFeedbackResponse:
      required:
        - status
        - message
      type: object
      properties: 
        status:
          type: string
          enum:
            - success
            - failure
          description: describes if endpoint hit is successful or not
        message:
          type: string
          description: A success message "request successful"  or a failure message describing the error faced, such as "Unknown error occoured".
          example: "Unknown error occoured"
          
    TaskFeedback:
      type: object
      required:
        - taskType
        - feedback
      properties:
        taskType:
            $ref: https://raw.githubusercontent.com/ULCA-IN/ulca/master/specs/common-schemas.yml#/components/schemas/SupportedTasks
        feedback:
          type: array
          description : list of
          items:
             $ref: '#/components/schemas/Feedback'
          
    Feedback:
      required:
        - feedbackQuestion
      type: object
      properties:
        feedbackQuestion:
          anyOf:
                - $ref: '#/components/schemas/PipelineFeedbackQuestions'
                - $ref: '#/components/schemas/TranslationFeedbackQuestions'
                - $ref: '#/components/schemas/AsrFeedbackQuestions'
                - $ref: '#/components/schemas/TtsFeedbackQuestions'

        isLiked:
          type: boolean
          description: indicates if user liked the output or not(Thumbs up/down flag)
        feedbackRating:
          type: integer
          description: rating provided to the feedback question in a scale of 5
          minimum: 1
          maximum: 5
        feedbackComment:
          type: string
          description: comment given on top of the rating
          example : The output generated is really impressive. Cheers to the model developers and crew!!
    
    PipelineFeedbackQuestions:
          type: string
          enum:
            - Pipeline feedback question 1
            - Pipeline feedback question 1
    TranslationFeedbackQuestions:
          type: string
          enum:
            - Translation feedback question 1
            - Translation feedback question 2
    AsrFeedbackQuestions:
          type: string
          enum:
            - ASR feedback question 1
            - ASR feedback question 2
    TtsFeedbackQuestions:
          type: string
          enum:
            - TTS feedback question 1
            - TTS feedback question 2