openapi: 3.0.1
info:
  title: ULCA - Pipeline Inference Endpoint Submission
  description: The documentation defines the schema in which pipeline inference endpoint details are to be submitted.
  contact:
    name: ekstep foundation
    email: contact@ekstep.org
  version: 1.0.0
servers:
  - url: /ulca
paths: {}
components:
  schemas:
    PipelineInference:
      required:
        - name
        - version
        - description
        - refUrl
        - domain
        - submitter
        - inferenceEndPoint
        - supportedPipelines
        - taskSpecifications
      type: object
      properties:
        name:
          maxLength: 100
          minLength: 3
          type: string
          description: model name that you want your users to see
          example: vakyansh asr model
        version:
          maxLength: 20
          minLength: 1
          type: string
          description: version for the model
          example: v1
        description:
          maxLength: 1000
          minLength: 25
          type: string
          description: brief description about model, its goal, basically something sweet about it
          example: Speech recognition model for classroom lecture
        domain:
          $ref: https://raw.githubusercontent.com/ULCA-IN/ulca/master/specs/common-schemas.yml#/components/schemas/Domain
        refUrl:
          maxLength: 200
          minLength: 5
          type: string
          description: github link or url giving further info about the model
          example: https://github.com/Open-Speech-EkStep/vakyansh-models
      
        submitter:
          $ref: https://raw.githubusercontent.com/ULCA-IN/ulca/master/specs/common-schemas.yml#/components/schemas/Submitter
        inferenceEndPoint:
          $ref: '#/components/schemas/InferenceAPIEndPoint'
        supportedPipelines:
          $ref: "#/components/schemas/ListOfPipelines"
        taskSpecifications:
          $ref: '#/components/schemas/TaskSpecifications'
    
    ListOfPipelines:
      type: array
      items: 
        $ref: "#/components/schemas/PipelineTaskSequence"
      
    PipelineTaskSequence:
        type: array
        items:
          anyOf: 
          $ref: https://raw.githubusercontent.com/ULCA-IN/ulca/master/specs/common-schemas.yml#/components/schemas/SupportedTasks

    InferenceAPIEndPoint:
      required:
        - callbackUrl
      type: object
      properties:
        callbackUrl:
          type: string
          format: url
        masterApiKey:
          required:
            - value
          type: object
          description: if endpoint needs authorization in headers to fetch output
          properties:
            name:
              type: string
              description: expected if the callbackurl requires an API key with a particular name. `Authorization` will be considered as default name if value is provided without a name
              default: Authorization
              example: apiKey
            value:
              type: string
              description: expected if the callbackurl requires an API key so as to fetch output
              example: dde19858-b354-4e24-8e92-a7a4b320c066
        isMultilingualEnabled:
          type: boolean
          default: false
          description: specify true if the same callbackUrl is capable of handling multiple languages
        isSyncApi:
          type: boolean
          description: specify true if the inference is a sync api, false otherwise. when false, specify the polling url and related properties
        asyncApiDetails:
          $ref: 'https://raw.githubusercontent.com/ULCA-IN/ulca/master/specs/model-schema.yml#/components/schemas/AsyncApiDetails'
        
      description: hosted location defines the end point of the model inference. specify a taskType along with Inference type

    TaskSpecifications:
      type: array
      items: 
        $ref: "#/components/schemas/TaskSpecification"

    TaskSpecification:
      required:
        - task
        - languages
      type: object
      properties:
        task:
          $ref: >-
            https://raw.githubusercontent.com/ULCA-IN/ulca/master/specs/common-schemas.yml#/components/schemas/ModelTask
        languages:
          $ref: '#/components/schemas/LanguagesList'

    LanguagesList:
      type: array
      items:
        $ref: '#/components/schemas/LanguageSchema'

    LanguageSchema:
      required:
        - sourceLanguage
      type: object
      properties:
        sourceLanguage:
          $ref: >-
            https://raw.githubusercontent.com/ULCA-IN/ulca/master/specs/common-schemas.yml#/components/schemas/SupportedLanguages
        targetLanguage:
            $ref: >-
              https://raw.githubusercontent.com/ULCA-IN/ulca/master/specs/common-schemas.yml#/components/schemas/SupportedLanguages
